#Rscript hic_trans_network_plotting.R 0 1
#Rscript hic_trans_network_plotting.R 0 2
#Rscript hic_trans_network_plotting.R 0 5
#Rscript hic_trans_network_plotting.R 0 10
#Rscript hic_trans_network_plotting.R 50 1
#Rscript hic_trans_network_plotting.R 50 2
#Rscript hic_trans_network_plotting.R 50 5
#Rscript hic_trans_network_plotting.R 50 10
#Rscript hic_trans_network_plotting.R 90 1
#Rscript hic_trans_network_plotting.R 90 2
#Rscript hic_trans_network_plotting.R 90 5
#Rscript hic_trans_network_plotting.R 90 10
Rscript hic_trans_network_plotting.R 98 1
Rscript hic_trans_network_plotting.R 98 2
Rscript hic_trans_network_plotting.R 98 3
Rscript hic_trans_network_plotting.R 98 4
Rscript hic_trans_network_plotting.R 98 5
